spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/momoservice?createDatabaseIfNotExist=true&useSSL=false
    username: haq
    password: 875690
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        formae_sql: true
  flyway:
    locations: classpath:db/migration

  mail:
    host: 0.0.0.0
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

server:
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always

