spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/momoservice?createDatabaseIfNotExist=true&useSSL=false
    username: haq
    password: 875690

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        formae_sql: true
  flyway:
    locations: classpath:db/migration

  mail:
    #    host: {Your smtp endpoint}
    #    port: {Your smtp port}
    #    username: {Your amazon SES username}
    #    password: {Your amazon SES smtp password}
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  boot:
    admin:
      client:
        url: [http://localhost:8080]
        username: hubert
        password: 878756
        instance:
          name: momoserviceApi

server:
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always
  port: 9000
  servlet:
    application-display-name: momoserviceApi
springdoc:
  swagger-ui:
    path: /
  api-docs:
    path: /api-docs
# Value config
mail:
  sent:
    #   from: {haqcall@gmail.com}
    subject: Confrim your email address


aws:
  s3:
    endpointUrl: https://s3.amazonaws.com
    #    accessKeyId: your access key Id
    #    secretKey: your secret key
    bucket:
      name: mobile-money-service-4989646462
    region: us-east-2

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    health:
      show-details: always


